### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by milebril** [p-en-o-cw-2017/p-en-o-cw-2017#2]
Is er mogelijkheid om een reset button toe te voegen? Om makkelijker en sneller meerdere tests te doen

**Comment by Wout12345** [comment]
Heb je al de nieuwe update geprobeerd? Als je de configuratie niet opnieuw moet ingeven denk ik niet dat heropstarten lang zou moeten duren ... Verder werkt het testbed naar mijn weten volledig deterministisch, dus ik zie het nut van meerdere identieke tests niet helemaal. Tenzij je elke keer een ander pad laat genereren?
